import { DEFAULT_SOUND_PACK, type SoundEvent, type SoundPack } from './soundTypes'

export type { SoundEvent, SoundPack }

/**
 * Sounds. Maplecord ships one pack, "Default", generated by tools/make-sounds.mjs (so it is original and free to
 * share). In the desktop app a user can add packs of their own as folders on their machine; those are listed here
 * once the main process reports them, and any event a pack lacks falls back to the default sound.
 */
let packs: SoundPack[] = []

export function setSoundPacks(found: SoundPack[]) { packs = found }

/** Names for the sound-pack picker: the built-in one first, then the user's own. */
export const soundPackNames = (found: SoundPack[] = packs) => [DEFAULT_SOUND_PACK, ...found.map(p => p.name)]

function urlFor(event: SoundEvent, packName: string): string {
  const file = packs.find(p => p.name === packName)?.events[event]
  // Packs are served by the desktop app from the user's own folder, through the same private scheme as plugin icons.
  if (file) return `maplecord-plugin://sounds/${encodeURIComponent(packName)}/${encodeURIComponent(file)}`
  return `/sounds/default/${event}.wav`
}

export function playSound(event: SoundEvent, pack: string, enabled: boolean) {
  if (!enabled) return
  try {
    const audio = new Audio(urlFor(event, pack))
    audio.volume = 0.8
    void audio.play().catch(() => { /* autoplay blocked until first interaction */ })
  } catch { /* no audio device */ }
}
